name: CI
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: 'python-version'
      - name: Install Python dependencies
        run: |
          python -m pip install -U setuptools wheel pip
          python -m pip install tox
      - name: Lint
        run: tox -e lint
      - name: Run Tests
        run: tox -e py37
